# generated by Grok AI
# list of chill profanity that are allowed

chill_profane_words = [
# Classic basics
"fuck", "fucking", "fucked", "fucker", "fuckers", "fucks", "fuckin", "fukin", "fck",
"motherfucker", "motherfuckers", "motherfucking", "mf", "mfer", "mfers",

# Shit family
"shit", "shitty", "shite", "shitting", "bullshit", "horseshit", "dipshit", "shithead",

# Ass family
"ass", "asses", "asshole", "assholes", "asshat", "asshats", "badass",

# Bitch family
"bitch", "bitches", "bitching", "bitchy", "sonofabitch", "son of a bitch",

# Dick/prick family
"dick", "dicks", "dickhead", "dickheads", "prick", "pricks",

# Other common chill ones
"damn", "damned", "goddamn", "goddamned", "goddammit",
"hell", "bloody hell",
"piss", "pissed", "pissing", "pissed off",
"crap", "crappy",
"bastard", "bastards",
"douche", "douchebag", "douchebags",
"jackass", "jackasses"
]