# generated by Grok AI
# list of slurs/hate speech that are banned

bad_words = [
# Racial/ethnic
"nigger", "nigga", "niggers", "niggas", "niglet",
"chink", "chinks", "chinky",
"spic", "spics", "spick",
"wetback", "wetbacks",
"kike", "kikes", "kyke",
"gook", "gooks",
"beaner", "beaners",
"coon", "coons", "coonskin",
"porchmonkey", "porchmonkeys",
"junglebunny", "jungle bunnies",
"towelhead", "towelheads",
"raghead", "ragheads",
"sandnigger", "sandniggers", "dune coon",
"paki", "pakis",
"wog", "wogs",

# Homophobic/transphobic
"faggot", "fag", "fags", "faggots", "fudgepacker",
"dyke", "dykes", "bull dyke",
"tranny", "trannies", "trap",
"shemale", "he-she",

# Ableist
"retard", "retarded", "retards", "tard", "tards",
"spaz", "spastic", "spastics",
"cripple", "crip", "cripples",
"mongoloid", "mong",

# Antisemitic/other
"heeb", "heebes", "hebe",
"zipperhead", "zipperheads",

# Explicit sexual/porn-related (weird/gross stuff to filter optionally)
"cunt", "cunts",
"cock", "cocks", "prick",
"tits", "titties", "boobs",
"twat", "twats",
"blowjob", "handjob", "rimjob",
"cum", "jizz", "semen", "nutted",
"pedophile", "pedo", "pedos", "child porn", "cp",
"rape", "raped", "rapist" # Often targeted as too dark/weird
]